### ISSUE TITLE
planned renaming

### ISSUE THREAD

**Issue by timkittel** [JuliaEnergy/PowerDynamics.jl#10]
Here is a list of suggested / planned renamings that will be executed before publication. (Result of discussion on gitlab.)

* [x] file `NetwirkRHSs.jl` to  `NetworkRHSs.jl`
* [ ]  `SystemSize` --> `systemsizeof`
* [ ]  `Nodes` --> `nodesof`
* [ ]  `AdmittanceLaplacian` --> `nodeadmittancesof` / `NodeAdmittance`
* [ ]  `LY` --> `NY`
* [ ]  `NetworkRHS` --> `rhsof`
* [ ]  `AbstractNodeDynamics.rhs/root` --> `rhsof(AbstractNodeDynamics)`
* [ ] instead of constructors, use `...of`, e.g. `GridDynamics` to `gridDynamicsOf`

**Comment by timkittel** [comment]
@FHell @luap-pik here are the planned renamings we discussed before on gitlab. I would try to to merge them in before our workshop, but I can't promise it.
Of course, if one of you would go through and do that, I would be happy (:

**Comment by janlisse** [comment]
Has become obsolete after big refactoring/rewrite.
