### ISSUE TITLE
Change in printing of typeof(t).name on 1.6 causes package errors

### ISSUE THREAD

**Issue by KristofferC** [JuliaEnergy/PowerDynamics.jl#117]
This package serializes type by using the result of `typeof(t).name`:

https://github.com/JuliaEnergy/PowerDynamics.jl/blob/39011ab401e61a045d13a49fe8b7fce9ef1c769b/src/parsers/JsonParser.jl#L98

which now errors on 1.6 since:

```jl
julia> PowerDynamics.SwingEq.name
typename(SwingEq)
```

Grabbing stuff from internal fields like `.name` can be brittle since these are subjects to change.

**Comment by JeffBezanson** [comment]
This should use `nameof` instead.

**Comment by luap-pik** [comment]
Thanks! You are completely right. :-)
