### ISSUE TITLE
examples folder in PowerDynamics.jl

### ISSUE THREAD

**Issue by SabineAuer** [JuliaEnergy/PowerDynamics.jl#119]
I really like having the PowerDynamicsExamples repo in order to connect this to binderhub but I think (similar to PyPSA) an examples folder directly in the PowerDynamics repo with only one or two files users can try out would be helpful. For example, adding a new feature it is possible to try it out with an example script right ahead.

**Comment by luap-pik** [comment]
We could make a SmallPowerGridExample system that we can also use for all the tests.

**Comment by SabineAuer** [comment]
I first thought of adding several small example files with different setup (more inverter based, purely conventional, mixed, islanded or connected to a higher grid-level) and could start a collection of different setups people can look into to get started easily with PowerDynamics.
But I also like to have an example grid that we could use for all tests. In any ways, all tests have somehow similar grids they rely on.

**Comment by antonplietzsch** [comment]
I made a PR (#136) for an examples folder in the PowerDynamics.jl repo including the IEEE 14-bus system. I think we should add some more example systems and also discuss how we can use these examples for testing.

- for the tests of this example I check that the DiffEq solvers give a `:Success`
- should we maybe also include tests to check that the simulation result is 'correct'?
- I plan to add the IEEE RTS-96 system (73 buses, 110 branches) soon
- @luap-pik could you maybe add an example for the CIGRE MV benchmark grid?
