### ISSUE TITLE
Old PD versions

### ISSUE THREAD

**Issue by luap-pik** [JuliaEnergy/PowerDynamics.jl#128]
I recently discovered that very old versions of PD.jl are still around in the package manager:

```julia
pkg> add PowerDyn...
PowerDynOperationPoint PowerDynBase            PowerDynamics           PowerDynSolve
```

@SabineAuer Is this intended?

**Comment by SabineAuer** [comment]
@luap-pik : yes, this is intended since some people still use these packages (e.g. from TU Delft) so we decided to keep them.

**Comment by luap-pik** [comment]
OK!
