### ISSUE TITLE
Support for SDAE

### ISSUE THREAD

**Issue by 910061035** [JuliaEnergy/PowerDynamics.jl#210]
I see the latest version of PowerDynamics.jl has not provided the method for defining stochastic differential equation (SDE)-based component. It may be my carelessness for finding this function as the latest version already has supported for SDE component, could you please check this for me?

**Comment by hexaeder** [comment]
Can you elaborate on that? There is no SDE capability in PowerDynamics. The closest thing are:

- [`FluctuationNodes`](https://github.com/JuliaEnergy/PowerDynamics.jl/blob/main/src/nodes/experimental/FluctuationNode.jl) whose power fluctuations follow at a predetermined timeseries, used in the two papers
  - https://pubs.aip.org/aip/cha/article-abstract/32/11/113114/2835976/Linear-response-theory-for-renewable-fluctuations?redirectedFrom=fulltext
  - https://arxiv.org/pdf/2303.06116.pdf
- also, there is a [simple SDE example in the underlying `NetworkDynamics.jl`](https://github.com/PIK-ICoNe/NetworkDynamics.jl/blob/main/examples/sde.jl) library

**Comment by 910061035** [comment]
> Can you elaborate on that? There is no SDE capability in PowerDynamics. The closest things are:
> 
> * [`FluctuationNodes`](https://github.com/JuliaEnergy/PowerDynamics.jl/blob/main/src/nodes/experimental/FluctuationNode.jl) whose power fluctuations follow at a predetermined timeseries, used in the two papers
>   
>   * https://pubs.aip.org/aip/cha/article-abstract/32/11/113114/2835976/Linear-response-theory-for-renewable-fluctuations?redirectedFrom=fulltext
>   * https://arxiv.org/pdf/2303.06116.pdf
> * also, there is a [simple SDE example in the underlying `NetworkDynamics.jl`](https://github.com/PIK-ICoNe/NetworkDynamics.jl/blob/main/examples/sde.jl) library

Thank you for your reply! I see in equation (25) of the arxiv pdf file that the SDE was used for modeling the power fluctuations. I want to define a nodal in PowerDynamic that is a scalar or multi-dimensional SDE to model the renewable component in power system.

**Comment by Anbue63** [comment]
I have performed the simulation in the paper that you are referring to. You are right that we used an SDE to model the renewable energy fluctuation time series. However, have fed the pre-generated time series into the `[FluctuationNodes]` that @hexaeder was talking about.

In case you are interested in the process you can find the script where I have performed the simulations here: https://github.com/PIK-ICoNe/SyntheticPowerGrid_Paper_Companion/blob/main/scripts/fluctuations_wind.jl

There is also a readme in the repo that tells you which packages you have to add to run the simulation.

**Comment by 910061035** [comment]
> I have performed the simulation in the paper that you are referring to. You are right that we used an SDE to model the renewable energy fluctuation time series. However, have fed the pre-generated time series into the `[FluctuationNodes]` that @hexaeder was talking about.
> 
> In case you are interested in the process you can find the script where I have performed the simulations here: https://github.com/PIK-ICoNe/SyntheticPowerGrid_Paper_Companion/blob/main/scripts/fluctuations_wind.jl
> 
> There is also a readme in the repo that tells you which packages you have to add to run the simulation.

Thank you.

**Comment by hexaeder** [comment]
I'll go ahead and close this issue, as it seems resolved. Feel free to comment again if you disagree.
