### ISSUE TITLE
Narrow dependency on DifferentialEquations.jl

### ISSUE THREAD

**Issue by janlisse** [JuliaEnergy/PowerDynamics.jl#28]
Since we currently only use ODE functionality from DifferentialsEquations.jl we could narrow
our dependency set. Instead of relying on the "full" DifferentialEquations" package we could use only
"OrdinaryDiffEq", see [http://docs.juliadiffeq.org/stable/features/low_dep.html](http://docs.juliadiffeq.org/stable/features/low_dep.html)

**Comment by janlisse** [comment]
Doe with https://github.com/JuliaEnergy/PowerDynamics.jl/pull/79

**Comment by SabineAuer** [comment]
Ok, I close the issue then
