### ISSUE TITLE
Three Phase Fault on a Bus

### ISSUE THREAD

**Issue by scdhulipala** [JuliaEnergy/PowerDynamics.jl#31]
Similar to the (simulate(Perturbation(2, :omega, Inc(0.2))) function, it would be helpful to have a function to simulate a three phase fault on a bus.

**Comment by FHell** [comment]
As a first step I have implemented NodeShortCircuit for a fault to ground, making use of the fact that the PiModels have shunts.

Currently this returns three solution objects, I also have some tentative code using call backs. Unfortunately that gives a very different result at the moment. Not sure why.

**Comment by luap-pik** [comment]
The implementation of `NodeShortCircuit` adds a shunt to a connecting line.
As long the line is static (and of type PiModelLine!!!), having the shunt there or at the node should be equivalent.
However, I strongly suggest to instead update the node shunt value `Y_n` in the callback and leave the line as is.

**Comment by luap-pik** [comment]
Since the component types are immutable and we cannot change field values, we more generally need a way to create a copy for the faulted component regardless of it's type.

**Comment by luap-pik** [comment]
closed with #93
