### ISSUE TITLE
Power Perturbation Simulation

### ISSUE THREAD

**Issue by scdhulipala** [JuliaEnergy/PowerDynamics.jl#32]
Any plans to include a function to perturb power of generator similar to speed (sim-
ulate(Perturbation(bus_number, :omega, Inc(perturbation)))?

**Comment by janlisse** [comment]
Hi @scdhulipala ,
we already have done some work regarding this feature on this branch: https://github.com/JuliaEnergy/PowerDynamics.jl/tree/PowerDrop
Can you have a look at the simulation signature and give some feedback if this matches with your use case/expectation?

**Comment by janlisse** [comment]
Done, see https://github.com/JuliaEnergy/PowerDynamics.jl/pull/45
