### ISSUE TITLE
Support specification of self-admittance for all node types

### ISSUE THREAD

**Issue by SabineAuer** [JuliaEnergy/PowerDynamics.jl#36]
changing from the admittance matrix representation (from PD 1.0) to the line types (in PD 2.0) raises the necessity to include self-admittance in the node equations for all the node types

**Comment by FHell** [comment]
What do you mean with this precisely? The Y_ii terms are now part of the line dynamics, so they are accounted for.

**Comment by SabineAuer** [comment]
I do not refer to the shunt admittance of the lines but rather to something like admittance-to-ground at a bus specifically to also include losses at nodes but not only for lines

**Comment by FHell** [comment]
Got ya. One way to model this right now is to connect the node to a ground node. A ground node could be modelled as a Slack bus with voltage amplitude 0.

**Comment by SabineAuer** [comment]
That's a good plan for now but I would like to have a more user-friendly and long-term solution. I thought, we could add Y_n as an optional argument to each node type and then let the node macro calculate the net current which would be total current from the lines minus the current from the nodal shunt losses. I wanted to get started with that beginning of next week.

**Comment by SabineAuer** [comment]
Done. see https://github.com/JuliaEnergy/PowerDynamics.jl/pull/49
