### ISSUE TITLE
Make checks on operation point search if no slack bus present

### ISSUE THREAD

**Issue by SabineAuer** [JuliaEnergy/PowerDynamics.jl#51]
Make more elaborate check than simple warning for systems without a slack bus

**Comment by luap-pik** [comment]
I believe this will be addressed in #88 .
However, it is an interesting question how we should treat the case when no slack is present.
We might have a look at the distributed slack implementation in [PyPsa](https://github.com/PyPSA/PyPSA/pull/107).

**Comment by SabineAuer** [comment]
I also think we can close this issue since it overlaps with #88.
