### ISSUE TITLE
Create architecture.md for PowerDynamics

### ISSUE THREAD

**Issue by SabineAuer** [JuliaEnergy/PowerDynamics.jl#52]
make reference to NetworkDynamics.jl

**Comment by luap-pik** [comment]
@SabineAuer What is supposed to be in there?

**Comment by SabineAuer** [comment]
The idea was to sketch the structure of PowerDynamics and how it is linked to NetworkDynamics. A few UML diagrams about the different components  and a description of the macros

**Comment by SabineAuer** [comment]
for inspiration: the gitlab architecture.md is nice: https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/doc/development/architecture.md

**Comment by luap-pik** [comment]
OK, I see. Shouldn't this be part of the docs?
