### ISSUE TITLE
Compatibilities

### ISSUE THREAD

**Issue by oskarddfa** [JuliaEnergy/PowerDynamics.jl#84]
I think the Project.toml file should be reviewed. Right now using PowerDynamics 2.3.0 is not trivial and Julia does not efficiently tell you what the problem is. 

What is the problem:
If you have any of the packages in the [compat] section of the Project.toml file already manually installed, and the version of the installed package is not listed in the compat section, then the PowerDynamics version with that Project.toml file cannot be installed. 

For example if I have RecipesBase 0.8.0 installed in my Julia environment, then I cannot install at the same time PowerDynamics 2.3.0 . Even more troubling is that if I have some Package that requires RecipesBase 0.8.0 I still cannot use PowerDynamics 2.3.0 and moreover Julia doesn't tell me which other package is causing the trouble. This is surely in my opinion some kind of bad behavior of Julia, but still this package should cope with that. 

A solution could be to extend the compatibilities to more versions of the single packages. Since it is mainly the packages with versions under "v1.0.0" causing the problem ( "^v1.0.0" implies compatibility with all the versions up to 1.9.9 and "^v0.1.0" implies compatibility only up to 0.1.9 and 0.x.x packages get often changed to formally incompatible versions, even though there happened no major change.), maybe more versions should be allowed for those. 
Moreover, I think that when submitting a new version it may be important to try to include also the latest version (if really compatible) of the packages in the compatibilities.

The packages that are outdated in the compat section are RecipesBase (now at 0.8),  Lazy (now at 0.15), Setfield (now at 0.6) , StaticArrays (now at 0.12).

Including multiple versions is possible like this: `RecipesBase = "0.7, 0.8"`.

**Comment by SabineAuer** [comment]
Does this PR solve the issue now? https://github.com/JuliaEnergy/PowerDynamics.jl/pull/94

**Comment by luap-pik** [comment]
@oskarddfa Can you explain what you mean by "I cannot install at the same time PowerDynamics 2.3.0"? I cannot reproduce that. For me, it installs the right PD version but downgrades RecipesBase.

I made a new environment and added `RecipesBase`which was installed as v1.0.0

`add PowerDynamics#master`  leaves me with 

```Julia
[cc46b21f] PowerDynamics v2.3.0 #master (https://github.com/JuliaEnergy/PowerDynamics.jl.git)
[3cdcf5f2] RecipesBase v0.7.0
```

whereas `add PowerDynamics#issue84`  results in 

```Julia
[cc46b21f] PowerDynamics v2.3.0 #issue84 (https://github.com/JuliaEnergy/PowerDynamics.jl.git)
[3cdcf5f2] RecipesBase v0.8.0
```

which is correct given the updated compat in #94
