### ISSUE TITLE
add bus names to node list

### ISSUE THREAD

**Issue by SabineAuer** [JuliaEnergy/PowerDynamics.jl#86]
instead of only having a line list and simply taking the entry as bus number we want to add bus names to the node list. This could look like

nodelist =[]
nodelist .add(“BusName”, SwingEq(...))
linelist=[]
linelist.add(“BusName1”,”BusName”,StaticLine(..))

This implies the json-format parser would need to be changed. We do not make the bus name mandatory but suggest to autgenerate the bus names if not given to not break the running json-import functionality

**Comment by luap-pik** [comment]
This could be achieved by passing dictionaries to construct the `PowerGrid`.
However, I have the tendency of placing this info in the component types, maybe by adjusting the macro?

**Comment by SabineAuer** [comment]
the issue is closed with the according PR
