### ISSUE TITLE
WIP: operation point search

### ISSUE THREAD

**Issue by luap-pik** [JuliaEnergy/PowerDynamics.jl#88]
(idea collection)

We need to develop a better operation point search that also needs to be more robust w.r.t
the initial guess. It should also have good performance for large systems.

Probably, it should be a multi-step approach consisting of 
1. good heuristics for initial values
2. automatic load flow solution
3. use 1 and 2 to get a compatible initial condition for the whole system, find a stable fixpoint

Research other options to solve power flow:
* PowerModels.jl (based on JuMP)
* interface to Panda Power 
* do we need HELM?

**Comment by luap-pik** [comment]
Also, GridCal has some good ressources to check:
https://gridcal.readthedocs.io/en/latest/theory/models.html

**Comment by SabineAuer** [comment]
I really like the idea of using a power flow software that is written in Julia already like (you suggested already) PowerModels.jl or  [PowerSimulations.jl](https://github.com/NREL/PowerSimulations.jl)

**Comment by luap-pik** [comment]
The following strategy to initialise the fixed point search seems to work well in various cases that I tested.

I define a `guess` that dispatches on the vertex type.
The default behaviour is to set the voltage indices to the slack voltage, 
assuming internal variables can be initialised at 0.

It is also possible to submit a power flow result, `v_vector` below.

```Julia
using PowerDynamics: AbstractNode
"""
Makes an type specific initial guess to help the operation point search.
The voltage is of all nodes is fixed to the voltage of the first SlackAlgebraic
in the system. The other symbols are set to zero.
Inputs:
    pg: Power grid, a graph containg nodes and lines
Outputs:
    guess: Type specific initial guess
"""
function initial_guess(pg)
    if SlackAlgebraic ∉ pg.nodes .|> typeof
        @warn "There is no slack bus in the system to balance powers."
    end

    sl = findfirst(SlackAlgebraic  ∈  pg.nodes .|> typeof)
    slack = pg.nodes[sl]

    type_guesses = guess.(pg.nodes, slack.U)
    return vcat(type_guesses...)
end

function initial_guess(pg, v_vector)
    type_guesses = guess.(pg.nodes, v_vector)
    return vcat(type_guesses...)
end


"""
guess(::Type{SlackAlgebraic}) = [slack.U, 0.]         #[:u_r, :u_i]
guess(::Type{PQAlgebraic}) = [slack.U, 0.]            #[:u_r, :u_i]
guess(::Type{ThirdOrderEq}) = [slack.U, 0., 0., 0.]   #[:u_r, :u_i, :θ, :ω]
"""
function guess(n::AbstractNode, slack_voltage)
    voltage = zeros(dimension(n))
    voltage[1] = real(slack_voltage)  #[:u_r, :u_i]
    voltage[2] = imag(slack_voltage)
    return voltage
end

function guess(n::SlackAlgebraic, slack_voltage)
    @assert n.U == slack_voltage
    return [real(n.U), imag(n.U)]
end
```

Then I do the operation point search using the `SteadyStateProblem` in DiffEq.

```Julia
function find_steady_state(pg, op_guess=nothing)
    if op_guess isa Nothing
        op_guess = initial_guess(pg)
    end
    ode = rhs(pg)
    op_prob = ODEProblem(ode, op_guess, (0.0, 1.0))
    sol = solve(
        SteadyStateProblem(op_prob),
        DynamicSS(Rodas5(); abstol = 1e-8, reltol = 1e-6, tspan = Inf),
    )
    return State(pg, sol.u)
end
```

Alternatively, you can also put the guess in `find_valid_initial_condition`
I did not find a case yet where one of the methods works and the other doesn't.

```Julia
function find_valid_initial_condition(pg, ic_guess)
    rr = RootRhs_ic(rhs(pg))
    nl_res = nlsolve(rr, ic_guess)
    if converged(nl_res) == true
        return nl_res.zero #State(pg, nl_res.zero)
    else
        println("Failed to find initial conditions on the constraint manifold!")
        println("Try running nlsolve with other options.")
    end
end
```

**Comment by SabineAuer** [comment]
@luap-pik: I think it would be great to open a PR for this and include the tests that you wrote. 
I think, it would be nice to make the function `initial_guess` optional and then transfer it to 
`find_valid_initial_condition`. I did not understand yet what `SteadyStateProblem` specifically does.

**Comment by luap-pik** [comment]
The `SteadyStateProblem` seems to be the DiffEq way of what we do ourselves by using NLsolve (e.g. `find_operationpoint`) when you call it with the `SSRootfind`. What I do above is, that I use the `DynamicSS`solver, which integrates the system until the state doesn't change anymore. The advantage is, that the steady state it finds should be stable. 

I suggest that `find_operationpoint` can get an additional argument to select between the two approaches. Since DiffEq is a dependency in any case, we could remove NLsolve from the list if we wanted to.

**Comment by SabineAuer** [comment]
Ok, that sounds neat. Do you want to realize this suggestion in a PR?
Eventually, you can also add your example test grid and (one that we can remove later) so I can run it also see that there are no differences in outcome. I also think, it is worthwile to then completely remove the NLSolve option if we can drop this dependency then.
