### ISSUE TITLE
LineShortCircuit + rename LineFault ? 

### ISSUE THREAD

**Issue by luap-pik** [JuliaEnergy/PowerDynamics.jl#91]
The name `LineFault` might create the impression that it creates a short circuit. What it does instead is actually removing a line. Maybe we can find a clearer name? 

`LineFailure` maybe?

Anyway, I see actually a larger implementation task when it comes to short circuits on lines.

Up to now `NodeShortCircuit` actually is a line short circuit at the _end_ of a line.
In practice, however, it can appear at any position. 
You can think of it as splitting the line in two with an algebraic shunt bus inbetween.
For a `PiModelLine`, it is straight-forward to calculate the equivalent resistances and construct a faulted pi model. 
But what about other types like transformers (different parameters, not obvious how to change the pi model) or dynamic lines? By now, I have to convert my model manually to include only `PiModelLine`s, this is quite hacky though.

I have the impression that an alternative could be to wrap the vertex/edge function of a faulted component and add the fault current on top, working for all types that return a current and have voltages as input.

Though the cleaner way might be to really "split" the line and add an algebraic constraint for the shunt in the middle.

@JuliaEnergy/powerdynamics  What are your thoughts on this?

**Comment by SabineAuer** [comment]
I do not mind renaming the LineFault. LineFailure sounds like a good suggestion to me
