### ISSUE TITLE
Interface PowerModels.jl for parsing files

### ISSUE THREAD

**Issue by luap-pik** [JuliaEnergy/PowerDynamics.jl#92]
E.g. load this into Julia: https://electricgrids.engr.tamu.edu/electric-grid-test-cases/activsg25k/

PowerModels can load the following formats:
+ MATPOWER 
+ PSS/E - PTI Format

**Comment by luap-pik** [comment]
@lekic-aleksandra How is it going? We can slo discuss here :-)

**Comment by lekic-aleksandra** [comment]
Thank you, Paul.
I wrote already my response on your mail.

Best regards,
Aleksandra Lekić

**Comment by luap-pik** [comment]
Hi Aleksandra,
to get the P,Q,V,phi set points we don't need to solve equations, I think. I guess we can just use the fact that they are already defined in PowerDynamics. An example for what I mean:

Let us define a SwingEq node
```julia
swing = SwingEq(H=H, P=P, D=D, Ω=Ω)
```

Here, `P` is the power set point. For the swing equation type it is assumed the the voltage set point is 1pu.
So we have `Pset = swing.P` and `Vset=1` for this type and `Q`and the angle are free variables to be solved for.

I imagine the following. We can define bus types like that
```julia
struct PV
   Pset
   Vset
end
```
 etc. and a conversion function for each node type

```julia
function convert_to_static(swing::SwingEq)
   return PV(swing.P, 1)
end
```

Then if you apply `convert_to_static` to all nodes you get the information about the type (PQ, PV, ...) and the set points and can fill them into the PowerModels dictionary.
